//! The Bengali dictionary Mukti carries with it.
//!
//! 451,348 words, compiled from `words.txt` at
//! `github.com/tahmid02016/bangla-wordlist` (Unlicense, public domain) by
//! `devtools/lexicon-build`. Stored as a finite-state automaton: 3.4 MB
//! embedded in the binary rather than 11 MB of plain text, with lookup in
//! O(length of the word) and no decompression step.
//!
//! # What this is for
//!
//! One question, asked over and over: **is this string an actual Bengali
//! word?** That question is what separates a real conversion from a fake one.
//! Bijoy maps the whole ASCII range, so *any* English sentence converts into
//! something Bengali-shaped; only genuine Bijoy converts into words a Bengali
//! reader would recognise.
//!
//! The 150 hand-written stems in [`crate::lexicon`] answer a weaker version of
//! the same question by substring match, and they will keep doing so until the
//! baseline measurement is published — replacing them before the harness runs
//! would mean improving something whose starting point was never recorded.
//!
//! # What it is not
//!
//! Not a spell checker and not an authority on correct Bengali. Membership
//! means "this string appears in a large word list", nothing more. Absence
//! means "not in this list", which for a rare or technical word is common and
//! is never on its own evidence that a conversion went wrong.

use std::sync::OnceLock;

use crate::roundtrip::normalise_nukta;

/// The compiled word list, built into the binary.
static SHIPPED_BYTES: &[u8] = include_bytes!("../data/bengali-words.fst");

/// 234,428 English words, for the opposite job: proving a word is **not**
/// Bijoy so it is left alone.
///
/// Compiled from `/usr/share/dict/words` — Webster's Second International,
/// whose 1934 copyright has lapsed, so it is public domain. It is built in
/// rather than read from the system at runtime because Windows has no such
/// file, and a guard that silently disappears on one platform is worse than
/// no guard at all.
static ENGLISH_BYTES: &[u8] = include_bytes!("../data/english-words.fst");

/// A set of Bengali words that can be asked whether it holds one.
pub struct Dictionary {
    set: fst::Set<&'static [u8]>,
}

impl Dictionary {
    /// The dictionary Mukti ships with.
    ///
    /// Built once on first use and shared thereafter. The automaton is read
    /// straight out of the binary, so this allocates nothing.
    pub fn shipped() -> &'static Dictionary {
        static SHIPPED: OnceLock<Dictionary> = OnceLock::new();
        SHIPPED.get_or_init(|| Dictionary {
            // The bytes are generated by our own tool and checked in beside
            // the source, so a failure here is a corrupted repository rather
            // than anything a caller could recover from.
            set: fst::Set::new(SHIPPED_BYTES).expect("the embedded dictionary is not a valid FST"),
        })
    }

    /// The English word list, used to protect readable English.
    pub fn english() -> &'static Dictionary {
        static ENGLISH: OnceLock<Dictionary> = OnceLock::new();
        ENGLISH.get_or_init(|| Dictionary {
            set: fst::Set::new(ENGLISH_BYTES)
                .expect("the embedded English list is not a valid FST"),
        })
    }

    /// Is this an ordinary English word?
    ///
    /// Case and surrounding punctuation are stripped first, so `Report,` and
    /// `THE` are recognised as readily as `report`.
    pub fn contains_english(&self, word: &str) -> bool {
        if !word.is_ascii() {
            return false;
        }
        let lower = word.to_ascii_lowercase();
        let bare = lower.trim_matches(|c: char| !c.is_ascii_lowercase());
        bare.len() >= 2 && self.set.contains(bare)
    }

    /// Is this an actual Bengali word?
    ///
    /// The nukta is composed before the lookup. `য়`, `ড়` and `ঢ়` are each
    /// legal in Unicode two ways — one character, or a base letter followed by
    /// U+09BC — and they look identical on screen. The dictionary stores only
    /// the precomposed spelling, so a caller holding the decomposed one would
    /// otherwise be told a perfectly ordinary word does not exist. That
    /// ambiguity has already cost this codebase four separate defects.
    pub fn contains(&self, word: &str) -> bool {
        self.set.contains(normalise_nukta(word))
    }

    /// How many words this dictionary holds.
    pub fn len(&self) -> usize {
        self.set.len()
    }

    /// Only ever false for the shipped dictionary; present because clippy asks
    /// for it wherever `len` exists, and because a caller-loaded one could be.
    pub fn is_empty(&self) -> bool {
        self.set.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_embedded_dictionary_loads_and_is_the_expected_size() {
        let d = Dictionary::shipped();
        // The exact count generated by `lexicon-build --mode shipped`. Pinned
        // so that regenerating the dictionary from a different source, or
        // silently shipping a truncated file, fails here rather than quietly
        // weakening every check that depends on it.
        assert_eq!(d.len(), 451_348);
    }

    #[test]
    fn ordinary_bengali_words_are_found() {
        let d = Dictionary::shipped();
        for word in ["কর্মসূচি", "প্রতিবেদন", "স্বাক্ষর", "নির্বাচন", "বিবরণ", "শিক্ষা"]
        {
            assert!(d.contains(word), "an ordinary word is missing: {word}");
        }
    }

    #[test]
    fn bengali_shaped_nonsense_is_not_found() {
        let d = Dictionary::shipped();
        // What English becomes when forced through the Bijoy tables. This is
        // exactly the case the dictionary exists to reject.
        for noise in ["ঈড়হংঁষঃধহঃ", "জরাবৎনধহশ", "চৎড়মৎধসসব", "অহহবী"]
        {
            assert!(
                !d.contains(noise),
                "nonsense was accepted as a word: {noise}"
            );
        }
        // And nothing that is not Bengali at all.
        for other in ["", "hello", "2026", "ঢাকা-Dhaka"] {
            assert!(!d.contains(other), "non-Bengali was accepted: {other:?}");
        }
    }

    #[test]
    fn a_word_is_found_whichever_way_its_nukta_is_written() {
        let d = Dictionary::shipped();
        // `সময়` ("time"), spelled both legal ways. Both must be found.
        let precomposed = "সম\u{09DF}";
        let decomposed = "সম\u{09AF}\u{09BC}";
        assert_ne!(precomposed, decomposed, "the two spellings differ as bytes");
        assert!(
            d.contains(precomposed),
            "the precomposed spelling is missing"
        );
        assert!(
            d.contains(decomposed),
            "the decomposed spelling was rejected"
        );
    }
}
