//! GRU953-Mukti mapping tables — GENERATED, DO NOT EDIT BY HAND.
//!
//! Ported from almehady/Bijoy-to-Unicode-File-Converter, MIT licensed; its
//! full licence text is reproduced in `THIRD-PARTY-LICENSES` at the root of
//! this repository and must be shipped with any distribution of this crate.
//!
//! Order is significant. Each table is applied top to bottom, so longer
//! conjuncts must be replaced before their shorter prefixes — `\u{995}\u{9CD}\u{9B7}\u{9CD}\u{9AE}`
//! before `\u{995}\u{9CD}\u{9B7}`. A hash map would destroy this and silently
//! corrupt output, which is why these are ordered slices.

/// Applied first: tidies duplicated glyphs and stray punctuation.
pub static PRE_MAP: &[(&str, &str)] = &[
    ("yy", "y"),
    ("vv", "v"),
    ("\u{00AD}\u{00AD}", "\u{00AD}"),
    ("y&", "y"),
    ("„&", "„"),
    ("‡u", "u‡"),
    ("wu", "uw"),
    (" ,", ","),
    (" |", "|"),
    ("\\ ", ""),
    (" \\", ""),
    ("\\", ""),
    ("\n\n\n\n\n", "\n\n"),
    ("\n\n\n\n", "\n\n"),
    ("\n\n\n", "\n\n"),
];

// 3 regex-only key(s) from PRE_MAP are handled in
// `normalise_whitespace()` instead: [' +', '\n +', ' +\n']

/// The main Bijoy glyph table. 190 entries, longest-first.
pub static CONVERSION_MAP: &[(&str, &str)] = &[
    ("Av", "আ"),
    ("A", "অ"),
    ("B", "ই"),
    ("C", "ঈ"),
    ("D", "উ"),
    ("E", "ঊ"),
    ("F", "ঋ"),
    ("G", "এ"),
    ("H", "ঐ"),
    ("I", "ও"),
    ("J", "ঔ"),
    ("K", "ক"),
    ("L", "খ"),
    ("M", "গ"),
    ("N", "ঘ"),
    ("O", "ঙ"),
    ("P", "চ"),
    ("Q", "ছ"),
    ("R", "জ"),
    ("S", "ঝ"),
    ("T", "ঞ"),
    ("U", "ট"),
    ("V", "ঠ"),
    ("W", "ড"),
    ("X", "ঢ"),
    ("Y", "ণ"),
    ("Z", "ত"),
    ("_", "থ"),
    ("`", "দ"),
    ("a", "ধ"),
    ("b", "ন"),
    ("c", "প"),
    ("d", "ফ"),
    ("e", "ব"),
    ("f", "ভ"),
    ("g", "ম"),
    ("h", "য"),
    ("i", "র"),
    ("j", "ল"),
    ("k", "শ"),
    ("l", "ষ"),
    ("m", "স"),
    ("n", "হ"),
    ("o", "ড়"),
    ("p", "ঢ়"),
    ("q", "য়"),
    ("r", "ৎ"),
    ("s", "ং"),
    ("t", "ঃ"),
    ("u", "ঁ"),
    ("0", "০"),
    ("1", "১"),
    ("2", "২"),
    ("3", "৩"),
    ("4", "৪"),
    ("5", "৫"),
    ("6", "৬"),
    ("7", "৭"),
    ("8", "৮"),
    ("9", "৯"),
    ("•", "ঙ্"),
    ("v", "া"),
    ("w", "ি"),
    ("x", "ী"),
    ("y", "ু"),
    ("z", "ু"),
    ("“", "ু"),
    ("–", "ু"),
    ("~", "ূ"),
    ("ƒ", "ূ"),
    ("‚", "ূ"),
    ("„„", "ৃ"),
    ("„", "ৃ"),
    ("…", "ৃ"),
    ("†", "ে"),
    ("‡", "ে"),
    ("ˆ", "ৈ"),
    ("‰", "ৈ"),
    ("Š", "ৗ"),
    ("|", "।"),
    ("&", "্\u{200C}"),
    ("^", "্ব"),
    ("‘", "্তু"),
    ("’", "্থ"),
    ("‹", "্ক"),
    ("Œ", "্ক্র"),
    ("”", "চ্"),
    ("—", "্ত"),
    ("˜", "দ্"),
    ("™", "দ্"),
    ("š", "ন্"),
    ("›", "ন্"),
    ("œ", "্ন"),
    ("Ÿ", "্ব"),
    ("¡", "্ব"),
    ("¢", "্ভ"),
    ("£", "্ভ্র"),
    ("¤œ", "ম্ন"),
    ("¤", "ম্"),
    ("¥", "্ম"),
    ("¦", "্ব"),
    ("§", "্ম"),
    ("¨", "্য"),
    ("©", "র্"),
    ("ª", "্র"),
    ("«", "্র"),
    ("¬", "্ল"),
    ("\u{00AD}", "্ল"),
    ("®", "ষ্"),
    ("¯", "স্"),
    ("°", "ক্ক"),
    ("±", "ক্ট"),
    ("²", "ক্ষ্ম"),
    ("³", "ক্ত"),
    ("´", "ক্ম"),
    ("µ", "ক্র"),
    // U+03BC GREEK SMALL LETTER MU, the visual twin of U+00B5 above.
    //
    // Both render as a mu and SutonnyMJ draws the glyph as ক্র, but only the micro
    // sign was mapped, so a document that happened to carry the Greek letter kept a
    // raw μ in its converted output -- বিক্রেতা came out as বিμেতা. Measured on
    // 19 August 2026 over 1,059 real documents: 105 words affected. Which of the two
    // a file contains depends on the keyboard driver and on what the word processor
    // substituted, so neither can be assumed.
    ("μ", "ক্র"),
    ("¶è", "ক্ষ্ণ"),
    ("¶", "ক্ষ"),
    ("·", "ক্স"),
    ("¸", "গু"),
    ("¹", "জ্ঞ"),
    ("º", "গ্দ"),
    ("»", "গ্ধ"),
    ("¼", "ঙ্ক"),
    ("½", "ঙ্গ"),
    ("¾", "জ্জ"),
    ("¿", "্ত্র"),
    ("À", "জ্ঝ"),
    ("Á", "জ্ঞ"),
    ("Â", "ঞ্চ"),
    ("Ã", "ঞ্ছ"),
    ("Ä", "ঞ্জ"),
    ("Å", "ঞ্ঝ"),
    ("Æ", "ট্ট"),
    ("Ç", "ড্ড"),
    ("È", "ণ্ট"),
    ("É", "ণ্ঠ"),
    ("Ê", "ণ্ড"),
    ("Ë", "ত্ত"),
    ("Ì", "ত্থ"),
    ("Í", "ত"),
    ("Î", "ত্র"),
    ("Ï", "দ্দ"),
    // 0xD0 is the conjunct ণ্ড, not a dash.
    //
    // It arrived as `-` from the upstream port and stood for a year, with FOCUS
    // recording the doubt and LESSONS §3 forbidding a change without evidence
    // from the font itself. That evidence now exists, from three directions:
    //
    // * the outline. Byte 0xD0 rendered from SutonnyMJ is the ণ্ড ligature. The
    //   whole archive word `gvb`Ð` drawn in SutonnyMJ reads মানদণ্ড, and drawn
    //   beside মানদণ্ড in a Unicode Bengali font it is the same word;
    // * the corpus. 0xD0 occurs 123 times in 27 distinct words across 37
    //   documents, every attributable run in SutonnyMJ. As `-` **none** of the
    //   123 produced a dictionary word — কর্মকা-ে, মানদ-, ঠা-া, অর্থদ-. As ণ্ড,
    //   104 of 123 do, and the remainder are run-split fragments that are still
    //   correct Bengali;
    // * the absence of a rival. 0xD1 is the em dash and 0xCA is an ornament, so
    //   nothing else in the font wants this slot.
    //
    // 0xD0 does not occur anywhere in the English negative corpus, so this adds
    // no false-positive surface.
    ("Ð", "ণ্ড"),
    ("Ñ", "-"),
    ("Ò", "\""),
    ("Ó", "\""),
    ("Ô", "'"),
    ("Õ", "'"),
    ("Ö", "্র"),
    ("×", "দ্ধ"),
    ("Ø", "দ্ব"),
    ("Ù", "দ্ম"),
    ("Ú", "ন্ঠ"),
    ("Û", "ন্ড"),
    ("Ü", "ন্ধ"),
    ("Ý", "ন্স"),
    ("Þ", "প্ট"),
    ("ß", "প্ত"),
    ("à", "প্প"),
    ("á", "প্স"),
    ("â", "ব্জ"),
    ("ã", "ব্দ"),
    ("ä", "ব্ধ"),
    ("å", "ভ্র"),
    ("æ", "ু"),
    ("ç", "ম্ফ"),
    ("è", "্ন"),
    ("é", "ল্ক"),
    ("ê", "ল্গ"),
    ("ë", "ল্ট"),
    ("ì", "ল্ড"),
    ("í", "ল্প"),
    ("î", "ল্ফ"),
    ("ï", "শু"),
    ("ð", "শ্চ"),
    ("ñ", "শ্ছ"),
    ("ò", "ষ্ণ"),
    ("ó", "ষ্ট"),
    ("ô", "ষ্ঠ"),
    ("õ", "ষ্ফ"),
    ("ö", "স্খ"),
    ("÷", "স্ট"),
    ("ø", "্ল"),
    ("ù", "স্ফ"),
    ("ú", "্প"),
    ("û", "হু"),
    ("ü", "হৃ"),
    ("ý", "হ্ন"),
    ("þ", "হ্ম"),
];

/// Applied last: fixes digits before a colon and similar details.
pub static POST_MAP: &[(&str, &str)] = &[
    ("০ঃ", "০:"),
    ("১ঃ", "১:"),
    ("২ঃ", "২:"),
    ("৩ঃ", "৩:"),
    ("৪ঃ", "৪:"),
    ("৫ঃ", "৫:"),
    ("৬ঃ", "৬:"),
    ("৭ঃ", "৭:"),
    ("৮ঃ", "৮:"),
    ("৯ঃ", "৯:"),
    (" ঃ", ":"),
    ("\nঃ", "\n:"),
    ("]ঃ", "]:"),
    ("[ঃ", "[:"),
    ("  ", " "),
    ("অা", "আ"),
    ("্\u{200C}্\u{200C}", "্\u{200C}"),
];
